# Generated by Django 4.1.2 on 2022-10-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_categories_no_of_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='images',
            field=models.ImageField(default=123, upload_to='jobimages'),
            preserve_default=False,
        ),
    ]
