# Generated by Django 4.1.2 on 2022-10-11 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_categories_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField()),
                ('documents', models.TextField()),
                ('skills', models.TextField()),
                ('language', models.TextField()),
                ('salary', models.TextField()),
                ('age', models.TextField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='web.categories')),
            ],
        ),
    ]
