# Generated by Django 4.1.2 on 2022-10-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
