# Generated by Django 4.1.2 on 2022-10-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_jobs_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='images',
            field=models.ImageField(default=1, upload_to='jobimages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='no_of_vacancy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
